"""
Report Generator – produces a Markdown compliance report from evaluation results.

Usage:
    python scripts/generate_report.py
"""

import sys
from pathlib import Path
from datetime import datetime, timezone

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from rules.rule_engine import load_json, save_json


BASE = Path(__file__).resolve().parent.parent


def main() -> None:
    # Load evaluation results
    eval_path = BASE / "outputs" / "evaluation_results.json"
    if not eval_path.exists():
        print("No evaluation results found. Run evaluate_compliance.py first.")
        sys.exit(1)

    eval_data = load_json(eval_path)
    results = eval_data["results"]
    run_info = eval_data["evaluation_run"]

    # Load scenario
    scenario = load_json(BASE / "case_study" / "scenario.json")

    # Build Markdown report
    lines: list[str] = []
    lines.append("# Compliance Evaluation Report")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Scenario:** {scenario['title']}")
    lines.append(f"**Sector:** {scenario['sector']}")
    lines.append(f"**Assessment Date:** {scenario['assessment_date']}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Rules evaluated | {run_info['rules_evaluated']} |")
    lines.append(f"| Evidence files | {run_info['evidence_files_loaded']} |")
    lines.append(f"| Total evaluations | {run_info['total_evaluations']} |")
    lines.append("")

    summary = run_info.get("summary", {})
    if summary:
        lines.append("### Compliance Status Distribution")
        lines.append("")
        lines.append("| Status | Count |")
        lines.append("|--------|-------|")
        for status, count in sorted(summary.items()):
            icon = {
                "compliant": "✓",
                "partially_compliant": "◐",
                "non_compliant": "✗",
                "not_assessed": "○",
            }.get(status, "?")
            lines.append(f"| {icon} {status} | {count} |")
        lines.append("")

    # Detailed results by domain
    lines.append("---")
    lines.append("")
    lines.append("## Detailed Results")
    lines.append("")

    # Group by domain
    by_domain: dict[str, list[dict]] = {}
    for r in results:
        domain = r.get("control_domain", "Unknown")
        by_domain.setdefault(domain, []).append(r)

    for domain, domain_results in sorted(by_domain.items()):
        lines.append(f"### {domain}")
        lines.append("")
        lines.append("| Requirement | Standard | Status | Details |")
        lines.append("|-------------|----------|--------|---------|")

        for r in domain_results:
            icon = {
                "compliant": "✓",
                "partially_compliant": "◐",
                "non_compliant": "✗",
                "not_assessed": "○",
            }.get(r["status"], "?")
            details = r.get("details", "").replace("|", "\\|")
            lines.append(
                f"| {r['requirement_id']} | {r['source_standard']} | {icon} {r['status']} | {details} |"
            )

        lines.append("")

    # Gaps and recommendations
    lines.append("---")
    lines.append("")
    lines.append("## Identified Gaps")
    lines.append("")

    gaps = [r for r in results if r["status"] in ("partially_compliant", "non_compliant")]
    if gaps:
        for g in gaps:
            lines.append(f"- **{g['requirement_id']}** ({g['source_standard']}): {g.get('details', 'No details')}")
            if g.get("missing_evidence"):
                lines.append(f"  - Missing/failed checks: {', '.join(g['missing_evidence'])}")
        lines.append("")
    else:
        lines.append("No gaps identified — all evaluated controls are compliant.")
        lines.append("")

    # Traceability
    lines.append("---")
    lines.append("")
    lines.append("## Traceability Matrix")
    lines.append("")
    lines.append("| Requirement | Standard | Rule | Evidence | Status |")
    lines.append("|-------------|----------|------|----------|--------|")
    for r in results:
        evidence_str = ", ".join(r.get("matched_evidence_ids", [])) or "None"
        lines.append(
            f"| {r['requirement_id']} | {r['source_standard']} | {r.get('rule_id', 'N/A')} | {evidence_str} | {r['status']} |"
        )
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*This report was generated by the AI-Driven Cybersecurity Governance Prototype. All data is synthetic.*")

    # Write report
    report_text = "\n".join(lines)
    report_path = BASE / "outputs" / "compliance_report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report_text, encoding="utf-8")
    print(f"Report written to {report_path}")

    # Also save as JSON for machine consumption
    report_json = {
        "report_generated": datetime.now(timezone.utc).isoformat(),
        "scenario": scenario["scenario_id"],
        "summary": summary,
        "gaps": [
            {
                "requirement_id": g["requirement_id"],
                "source_standard": g["source_standard"],
                "status": g["status"],
                "details": g.get("details"),
                "missing_evidence": g.get("missing_evidence", []),
            }
            for g in gaps
        ],
        "total_evaluations": len(results),
    }
    save_json(report_json, BASE / "outputs" / "compliance_report_summary.json")
    print(f"JSON summary written to {BASE / 'outputs' / 'compliance_report_summary.json'}")


if __name__ == "__main__":
    main()
